server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # все маршруты на index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Прокси на Go сервер
    location ~ ^/(shapes|calculate|history) {
        proxy_pass http://server:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
